[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=62.4.0", "wheel" ]

[project]
authors = [ { email = "mathis.brossier@gmail.com", name = "Mathis Brossier" } ]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
description = "WESL (WGSL Extended) grammar for tree-sitter"
keywords = [ "incremental", "parsing", "tree-sitter", "wesl" ]
license.text = "MIT"
name = "tree-sitter-wesl"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[project.urls]
Homepage = "https://webgpu-tools/tree-sitter-wesl"

[project.optional-dependencies]
core = [ "tree-sitter~=0.24" ]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
